version: "3"

services:

  bookstore_db:
    container_name: bookstore_db
    image: "postgres"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env


  bookstore:
    container_name: bookstore
    image: shuaibu12345/go-bookstore:1.0.0
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - bookstore_db
    deploy:
      mode: replicated
      replicas: 1
    # environment: 
    #   WEB_PORT: ${WEB_PORT}
    #   DB_PORT: ${DB_PORT}
    #   DB_USER: ${DB_USER}
    #   DB_PASSWORD: ${DB_PASSWORD}
    #   DB_NAME: ${DB_NAME}
    env_file:
      - .env

volumes:
  postgres: {}
